CREATE SEQUENCE "PUBLIC"."SEQUENCE_USER" START WITH 10 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SEQUENCE_PHONE" START WITH 10 BELONGS_TO_TABLE;

DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS USER;

CREATE MEMORY TABLE "PUBLIC"."USER"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SEQUENCE_USER" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SEQUENCE_USER",
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP,
    "ACTIVE" BOOLEAN,
    "EMAIL" VARCHAR(255),
    "LAST_LOGIN" TIMESTAMP,
    "NAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "TOKEN" VARCHAR(255),
    "UUID" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");

CREATE MEMORY TABLE "PUBLIC"."PHONE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SEQUENCE_PHONE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SEQUENCE_PHONE",
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP,
    "CITYCODE" VARCHAR(255),
    "CONTRYCODE" VARCHAR(255),
    "NUMBER" VARCHAR(255),
    "USER_ID" BIGINT
);

ALTER TABLE "PUBLIC"."PHONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");
ALTER TABLE "PUBLIC"."PHONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;

INSERT INTO "PUBLIC"."USER" (ID,CREATED_AT, UPDATED_AT, ACTIVE, EMAIL, LAST_LOGIN, "NAME", PASSWORD, TOKEN, UUID)
VALUES (1, NOW(), NOW(), 1, 'email@existente.cl', NOW(), 'Usuario Prueba', '$2a$10$4NjGf1lfS3u4O.PVucprsunULExsEIKP.vlR200t57hSfZ4Nx61iq', 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqdWFuQHJvZHJpZ3Vlei5vcmd4IiwiZXhwIjoxNjM0NzA2MDYxLCJpYXQiOjE2MzQ2ODgwNjF9.BijMpBku4rAhz4-laA70cTXTu3uXeaKNfWEEKjuPshE-RGecEY0LRiwWH7FzJ_Oa1P6KBwnwKU9KX_H1mHSVJg', '047b3d22-87c2-4fd7-b5cf-6fba1d943aa9');

INSERT INTO "PUBLIC"."PHONE"(ID,CREATED_AT, UPDATED_AT, CITYCODE, CONTRYCODE, "NUMBER", USER_ID)
VALUES (1, NOW(), NOW(), '56', '2', '324234', 1);

